version = 0.1

[default.deploy.parameters]
stack_name = "naute"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.build.parameters]
cached = true

[default.validate.parameters]
lint = true
